### ISSUE TITLE
LaTeXML with current Fedora 38 beta LaTeX causes infinite (?) loop

### ISSUE THREAD

**Issue by flyn-org** [brucemiller/LaTeXML#2064]
I process LaTeX on Fedora 38 beta using LaTeXML. Recently, I started observing that some latexml runs seem to enter in infinite loop. I spent some time narrowing this down until I arrived at the following minimum example:
```
\documentclass{article}
\usepackage{siunitx}
\begin{document}
\end{document}
```
When I run `latexml foo.tex`, the conversion hangs with:
```
latexml (LaTeXML version 0.8.7) processing foo.tex
Package: expl3
 Digesting > Processing > Loading > Loading > Loading > Processing > Processing definitions /usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex
```
Removing in import of `siunitx` fixes the problem. My Fedora 38 beta install provides LaTeXML-0.8.7-1.fc38.noarch and texlive-l3kernel-svn65299-65.fc38.noarch.

**Comment by dginev** [comment]
@flyn-org could you share the output of `pdflatex --version` as well on that machine?

I suspect this is a fresh regression due to the upstream texlive.

**Comment by flyn-org** [comment]
Here is the output from `pdflatex --version`:
```
pdfTeX 3.141592653-2.6-1.40.24 (TeX Live 2022)
kpathsea version 6.3.4
Copyright 2022 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.13; using zlib 1.2.13
Compiled with xpdf version 4.04
```
I just found that if I leave the LaTeXML process running long enough, it eventually terminates with:
```
latexml (LaTeXML version 0.8.7) processing foo.tex
Package: expl3
Error:expected:Match:? Missing argument Match:? for Core::Definition::Expandable[\??? Match:?] at expl3-code.tex; line 32108 col 0
Error:expected:Match:? Missing argument Match:? for Core::Definition::Expandable[\??? Match:?] at expl3-code.tex; line 32108 col 0
[...]
Error:expected:Match:? Missing argument Match:? for Core::Definition::Expandable[\??? Match:?] at expl3-code.tex; line 32108 col 0
Error:expected:Match:? Missing argument Match:? for Core::Definition::Expandable[\??? Match:?] at expl3-code.tex; line 32108 col 0
Fatal:too_many_errors:100 Too many errors (> 100)!
	at expl3-code.tex; line 32108 col 0 - line 32108 col 5
	In Core::Definition::Expandable[\??? Mat... /usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3-code.tex; from line 10718 col 0 to line 10718 col 33
Conversion failed 101 errors; 1 fatal error (See /tmp/foo.latexml.log) (reqd. 27m 22.74s)
```
Line 32108 of `expl3-code.tex` is the closing brace for the following statement:
```
  \ior_str_map_inline:Nn \g__codepoint_data_ior
    {
      \reverse_if:N \if:w \c_hash_str \tl_head:w #1 \c_hash_str \q_stop
        \__codepoint_data_auxi:w #1 \q_stop
      \fi:
    }
```

**Comment by ehuelsmann** [comment]
@flyn-org what is the Perl version on Fedora 38? LaTeXML 0.8.7 doesn't seem to work on Ubuntu Lunar (the unreleased next release). It has Perl 5.36; whereas I'm perfectly able to run 0.8.7 on Ubuntu Jammy (22.04 / 22.10)

**Comment by flyn-org** [comment]
```
$ rpm -q perl
perl-5.36.0-495.fc38.x86_64
```

**Comment by brucemiller** [comment]
It indeed is in expl3; more recent versions are doing *much* more (pre)processing of Unicode information which is currently causing a huge slowdown, and then errors. It's not actually an infinite loop, however.  Still debugging...

**Comment by neilt** [comment]
We are still experiencing this slowdown. It is currently taking over 22 minutes to build the XML with Tex Live 2024 and LaTeXML 0.8.8 for https://github.com/ehuelsmann/ledgersmb-book. We have limited our CI tests to Tex Live 2022 and LaTeXML 0.8.7 for now, but that will eventually not be acceptable. We would appreciate any progress possible on this huge slowdown.

**Comment by dginev** [comment]
> that will eventually not be acceptable. We would appreciate any progress possible on this huge slowdown.

We agree wholeheartedly. But I have to moderate expectations that the current situation will likely not improve before v0.8.9, since the necessary upgrades are rather significant.

**Comment by vincentzlt** [comment]
Any update on this issue? Or what should I do to not using the expl3 feature? I found there are no `\usepackage{expl3}` in my code but still experiencing similar problem..

**Comment by dginev** [comment]
@vincentzlt as per my last comment - we're still at v0.8.8, so no expected major updates to the situation.

If you can avoid `expl3` use with latexml for now - you should - as you will encounter a performance penalty at the least, and regressions at the worst. Recent PRs are inching us closer to a sped up setup, but still some ground to cover.

**Comment by ehuelsmann** [comment]
Any progress on the issue? If there's something others can do to help, that'd be very welcome feedback: the issue is problematic for our project, because we don't directly depend on expl3...

Would it be an idea to write some of the checks as a Perl XS module to increase performance?

**Comment by teepeemm** [comment]
@ehuelsmann  The `expl3` issue was likely fixed with #2525, but a subsequent commit unfixed it.  It sounds like there is a patch, but it won't be applied until the federal government reopens (see the end of that thread).

`siunitx` still needs some work to accept version 3 syntax.  I think I'm close on that.

**Comment by dginev** [comment]
Indeed, this is pending the v0.9 release of latexml, pre-compiling the kernel makes these cases much faster.

As to:
> Would it be an idea to write some of the checks as a Perl XS module to increase performance?

This was tried circa 2012-2013 (there are some old issues and PRs here exploring trade-offs). It is very painful to maintain an XS port. Instead, it is seemingly lower difficulty to port latexml to Rust. But work in that direction is currently frozen due to redirected effort. Generally circumstances have slowed us in 2025 a little more than usual.

**Comment by brucemiller** [comment]
This should *essentially* be fixed, but we still have some logistic issues to sort out.  LaTeXML now has a `make formats` (to be done after `make`), analogous to `initex`, which preprocesses `plain.tex, latex.ltx`. With later texlive, this may take 10-ish minutes to complete, but after this, the tests (or any use, direct or indirect, of the latex 3 kernel) complete in reasonable(ish) time.

For package maintainers, where LaTeXML already has a dependence on the systems texlive, it would be expected to add `make formats` into the `spec` (or `deb`) recipe.
