### ISSUE TITLE
Tikz automata not processed properly

### ISSUE THREAD

**Issue by kaagithub** [brucemiller/LaTeXML#770]
The tikz graphics are not rendered at all-- these are mostly automata
like the including file, which compiles well with pdflatex and gives the epub included:
latexml testTikz.tex --dest=testTikz.epub

[testTikz.zip](https://github.com/brucemiller/LaTeXML/files/328681/testTikz.zip)

**Comment by dginev** [comment]
Thanks for the report and the minimal test case!

**Comment by brucemiller** [comment]
Your test case seems to work fine here, at least for the current github version (I have some local changes but shouldn't be affecting this case).

But also, to create an epub, you'd want to use the latexml*c* program, not latexml itself:
```
latexmlc testTikz.tex --dest=testTikz.epub
```
which also works for me.

The way you ran it, it only produce LaTeXML's XML file which happened to be named .epub instead of .xml.  Incidentally the contents of that XML suggest that LaTeXML didn't find the tikz libraries? Not sure...

**Comment by kaagithub** [comment]
Hi,

Thank you for your help and test.

I'm on Ubuntu, so I installed the package that's in it (v 0.7.0).
I do not seem to have latexmlc installed and it does not exist in the 
Ubuntu repository.

What should I do? Install the latest version? Is latexmlc in it?

K

**Comment by dginev** [comment]
Hi @kaagithub ,

Yes, please install the version from GitHub, so that we avoid looking at problems that have been fixed in the past. By now 0.7.0 is incredibly outdated. There is an upcoming release of version 0.8.2, and we should probably contact the Debian maintainers to update the available latexml as well, as it has been about a couple of years since the last update (if memory servers me right).

Thanks!

**Comment by kaagithub** [comment]
Hi @dginev,

I just followed the doc on http://dlmf.nist.gov/LaTeXML/get.html...
So you should probably update the Web site too.

Thanks!

**Comment by kaagithub** [comment]
Hi all,

I installed the GitHub version and it works much better! Thanks a lot!

However, there is still an issue with the node numbering (the numbers appear outside the node).
Is it a problem from my version?

[testTikz.epub.zip](https://github.com/brucemiller/LaTeXML/files/331433/testTikz.epub.zip)

**Comment by brucemiller** [comment]
I'm confused about ubuntu/debian giving you that ancient version 0.7.0, but I'm not familiar with debians way of doing things.  Googling "debian latexml" shows that there are versions 0.7.0 "wheezy (oldstable)", but also 0.8.1 "sid (unstable)".  Do you have to do something special to get the unstable version?

I looked at your epub and it looks fine to me. On Fedora 22, it opens with atril and looks the same as the pdf (somewhat surprisingly! :> ) and the html version that I'd made before (in Firefox). Maybe the errors of my viewers are compensating for the errors in LaTeXML?  How are you viewing it?

**Comment by kaagithub** [comment]
As for Ubuntu I'm using the LTS (long term support), the most stable one. I will not switch to the unstable version, like most users I prefer a stable system ;-)
I had no pb building it from the sources so I suppose you should advise Ubuntu LTS users to do so.

I use the Firefox plugin as a viewer (I never thought it could come from the viewer) and you're right, it looks perfect (??) on Calibre!

Waoooh!
It's beautiful!

Latexml is just great!! Thank you so much!!

**Comment by dginev** [comment]
That's great news! Closing here :+1:

**Comment by brucemiller** [comment]
Actually the "Get LaTeXML" page did mention that it was in the unstable repo; I've added a warning that the stable repo may hold a very old version.  Thanks!
